export const MOCK_DATA = [
  {
    id: 1,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 2,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 3,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 4,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 5,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 6,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 7,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 8,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 9,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 10,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 11,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 12,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 13,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 14,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 15,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 16,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 17,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 18,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 19,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
  {
    id: 20,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    approveInterview: true,
    status: '최종 합격',
  },
];
