const LONG_TEXT =
  '엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 글엄청나게 긴 ';

export const MOCK_DATA = [
  {
    uid: 1,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'FAIL_PAPER',
  },
  {
    uid: 2,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'FAIL_PAPER',
  },
  {
    uid: 3,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 4,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL_PAPER',
  },
  {
    uid: 5,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'PASS',
  },
  {
    uid: 6,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 7,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 8,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 9,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 10,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'PASS_PAPER',
  },
  {
    uid: 11,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'PASS_PAPER',
  },
  {
    uid: 12,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'PASS_PAPER',
  },
  {
    uid: 13,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'PASS_PAPER',
  },
  {
    uid: 14,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 15,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 16,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 17,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL_PAPER',
  },
  {
    uid: 18,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL_PAPER',
  },
  {
    uid: 19,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 20,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'PASS',
  },
];

export const DETAIL = {
  name: '홍길동',
  sid: '201300033',
  major: '컴퓨터공학',
  gpa: '3.5',
  position: 'FE',
  algorithm: '백준 3수준',
  phone: '010-3035-5265',
  project: '조금 있는 수준입니다.',
  link: 'https://github.com/Collection50',
  enhancement: LONG_TEXT,
  level: LONG_TEXT,
  pros: LONG_TEXT,
  goal: LONG_TEXT,
  completion: LONG_TEXT,
};
