export const MOCK_DATA = [
  {
    uid: 1,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'FAIL_PAPER',
  },
  {
    uid: 2,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'FAIL_PAPER',
  },
  {
    uid: 3,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 4,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL_PAPER',
  },
  {
    uid: 5,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'PASS',
  },
  {
    uid: 6,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 7,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 8,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 9,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 10,
    name: '김길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'PASS_PAPER',
  },
  {
    uid: 11,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'PASS_PAPER',
  },
  {
    uid: 12,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'PASS_PAPER',
  },
  {
    uid: 13,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'PASS_PAPER',
  },
  {
    uid: 14,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 15,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 16,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 17,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL_PAPER',
  },
  {
    uid: 18,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'CHECK',
    applicationStatus: 'FAIL_PAPER',
  },
  {
    uid: 19,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'FAIL',
  },
  {
    uid: 20,
    name: '이길동',
    GPA: '3.5',
    grade: 3,
    career: 'BE',
    interviewDate: '2013.08.18 18:00',
    interviewStatus: 'UNCHECK',
    applicationStatus: 'PASS',
  },
];
